### PR TITLE
Async directory read fix

### PR DESCRIPTION
**Pull request by loganetherton**
I had two people report to me that the nested directories weren't being read correctly. It's not immediately apparent why this would be the case, but the sync functions were behaving a bit async-y.

I got the reporters to put some debugging code in place, and what was happening was that when a request type directory was read, the next request method began before all files could be required. Clearly it wasn't as blocking as I had thought!

Either way, the change in this pull requests has resolved the problem for everyone I've spoken with so far.

In truth, I probably should have rewritten the whole function to return a complete array from walkSync, but the last time done() is called it's going to pass the complete array anyhow, and I didn't think anyone would mind the extra 5ms startup time. =)

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for the report and the PR! Maybe it's even better to abstract this out and use some existing solution for this, like [node-walk](https://github.com/coolaj86/node-walk) or [node-require-directory](https://github.com/troygoode/node-require-directory). What do you think?

**Comment by loganetherton** [comment]
That's not a bad idea at all. Since it's caused issues already, it would be
worth a shot. I'm happy to check it out in the upcoming days, if you would
like. I'll never turn down a distraction during work hours. ;)

**Comment by webpro** [comment]
Hey @loganetherton, any chance you'd still give this a shot? :-)

**Comment by loganetherton** [comment]
Sure, I can help out. I've got a bunch of code review stuff this week, so it'll probably be this weekend. I'll look into what it would take. =)

**Comment by webpro** [comment]
@loganetherton, I just had a shot at it already. This should work now in the latest 0.6.0 release. Thanks for the help!

**Comment by loganetherton** [comment]
Ah, you beat me to it! 

Well, I'm happy to help if you ever need it in the future. Keep up the awesome work!

**Pull request closed without merging**
